name: cyberking_capitals
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/logo/
    - images/icons/
    - images/authentication/
    - images/onboarding/